pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Quindart/TravelSummonerRift.git'
            }
        }

        stage('Copy .env file') {
            steps {
                configFileProvider([configFile(fileId: 'Struct-and-design-software', targetLocation: '.env')]) {
                    sh 'ls -la && cat .env' // Kiểm tra file có tồn tại không?
                }
            }
        }

        stage('Build and Restart Services') {
            steps {
                script {
                    sh '''
                    cd docker
                    docker-compose down
                    docker-compose up --build -d 
                    '''
                }
            }
        }
    }
}
