pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'loc', url: 'https://github.com/Quindart/TravelSummonerRift.git'
            }
        }
    }
}
