pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'loc', url: 'https://github.com/Quindart/TravelSummonerRift.git'
            }
        }
    }
    stage('Build and Restart Services') {
            steps {
                script {
                    sh '''
                    docker-compose down
                    docker-compose up --build -d
                    '''
                }
            }
        }
}
