server:
  port: 8080
  address: ${GATEWAY_URL}

app:
  api-prefix: /api/v1
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"  # Chỉ cần dòng này
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: identity_service
          uri: http://localhost:5723
          predicates:
            - Path=${app.api-prefix}/user-service/**
          filters:
            - StripPrefix=2
        - id: booking_service
          uri: http://localhost:1902
          predicates:
            - Path=${app.api-prefix}/booking-service/**
          filters:
            - StripPrefix=2
    zookeeper:
      config:
        enabled: false
        import-check:
          enabled: false